### ISSUE TITLE
Restlet JAX-RS deserializes into ArrayList<LinkedHashMap>

### ISSUE THREAD

**Issue by RedTailedHawk** [restlet/restlet-framework-java#1304] opened 2018-01-04 14:42 UTC
I started using the Restlet JAX-RS extension, but I'm finding that lists get deserialized into an `ArrayList` of `LinkedHashMap` instead of the class.

    @Path("MyService")
    public class MyService {
        @POST
        @Consumes(MediaType.APPLICATION_JSON)
        @Produces(MediaType.APPLICATION_JSON)
        @Path("myTestMethod")
        public String testIt(final List<MyTestClass> myList) {
            return "hello";
        }
    }

    public class MyTestClass {
        @JsonProperty("name")
        private String name;
    }

Any ideas on how to have Jackson deserialize into `List<MyTestClass>`?  It works fine when I don't use the JAX-RS extension, but I need this to port over some existing web services.

Thanks for any help.

==Update==

Sending data like this:

    import requests
    import json

    url = "http://localhost:8182/MyService/myTestMethod"

    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    request_object = [{"name": "joe"}, {"name": "bill"}]

    params = json.dumps(request_object)

    response = requests.post(url, data=params, headers=headers)

**Comment by thboileau** [comment] 2018-01-09 13:01
Hello @RedTailedHawk 
I wonder which version of the Restlet Framework are you using?

**Comment by RedTailedHawk** [comment] 2018-01-09 13:53
Sorry, I should have posted that.  It's version `2.3.9`.

**Comment by thboileau** [comment] 2018-01-09 14:46
Hello @RedTailedHawk 

I've tested on my side with this sample code which seems to work fine. could you confirm?

[test-jaxrs.zip](https://github.com/restlet/restlet-framework-java/files/1615444/test-jaxrs.zip)

**Comment by RedTailedHawk** [comment] 2018-01-09 15:01
Thanks @thboileau, I just ran your code and am seeing an `ArrayList` of `LinkedHashMap`, so it's consistent with the issue I reported.

**Comment by thboileau** [comment] 2018-01-09 18:14
thanks, I see now. The issue is that the converter has to know which implementation of List he will use. and by default, he does not know.

As a workaround, you can declare your method as follow:
```java
public String testIt(final MyTestClass[] myList) {
}
```

**Comment by thboileau** [comment] 2018-01-10 07:59
The issue is to tell the Jackson object mapper which is the precise target type and at the same time, keep generic the signature of the function.
let's think about it.

**Comment by jlouvel** [comment] 2024-05-11 23:26
Closing as we are removing JAX-RS in branch 2.5

**Closed by jlouvel** 2024-05-11 23:26 UTC
Labels: Extension: JAX-RS, Type: bug
