### ISSUE TITLE
Introspector : ApiSpark returns 500

### ISSUE THREAD

**Issue by komasoftware** [restlet/restlet-framework-java#1032] opened 2015-02-26 10:45 UTC
I am trying to push my API to ApiSpark, but the server return 500. I am running :

`org.restlet.ext.apispark.Introspector -u myuserid -p mypasswd -n --id v1 com.klawt.server.ApiBootLoader`

where `ApiBootLoader extends org.restlet.Application`

`Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request`

```
SEVERE: Introspection error
java.lang.RuntimeException: APISpark server encounters some issues, please try later
    at org.restlet.ext.apispark.internal.utils.IntrospectionUtils.sendDefinition(IntrospectionUtils.java:162)
    at org.restlet.ext.apispark.Introspector.process(Introspector.java:299)
    at org.restlet.ext.apispark.Introspector.main(Introspector.java:91)
Caused by: Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
    at org.restlet.resource.ClientResource.doError(ClientResource.java:590)
    at org.restlet.resource.ClientResource.handleInbound(ClientResource.java:1153)
    at org.restlet.resource.ClientResource.handle(ClientResource.java:1048)
    at org.restlet.resource.ClientResource.handle(ClientResource.java:1065)
    at org.restlet.resource.ClientResource.post(ClientResource.java:1466)
    at org.restlet.ext.apispark.internal.utils.IntrospectionUtils.sendDefinition(IntrospectionUtils.java:115)
    ... 2 more
```

**Comment by komasoftware** [comment] 2015-02-26 11:03
``org.restlet.ext.apispark.Introspector -u myuserid -p mypasswd  --create-descriptor com.klawt.server.ApiBootLoader`` returns 

``Unprocessable Entity (422) - The server understands the content type of the request entity and the syntax of the request entity is correct but was unable to process the contained instructions``

**Comment by thboileau** [comment] 2015-02-27 08:28
Hi @komasoftware, my understanding is that the first request (``org.restlet.ext.apispark.Introspector -u myuserid -p mypasswd -n --id v1 com.klawt.server.ApiBootLoader``) fails because the value provided for the `id` parameter is wrong. It should be something like a number `1234` and references the identifier of one of your Wab API available from your dashboard.
I notice that the platform should not return a basic 500 error, but give more details. I create an issue for the dev team.

**Comment by thboileau** [comment] 2015-02-27 08:33
Regarding the second issue, I would to know what version of Restlet Framework are you using?

**Comment by komasoftware** [comment] 2015-02-27 08:37
I am on branch 2.3.
But I think for the second issue, I also need to pass in some parameter then to refer to my WEB API in the dashboard ?

**Comment by thboileau** [comment] 2015-02-27 09:43
Regarding the second issue, I had a look a the logs, I don't see 422 status responses. I wonder if this is an error on client side.

To my mind the command line is fine. It intends to create a "web api descriptor" that corresponds to the application called "com.klawt.server.ApiBootLoader".
I've a test using one sample code taken from the tutorials repository (https://github.com/restlet/restlet-tutorial) which worked for me:
-u myuserid -p mypasswd --create-descriptor org.restlet.tutorial.WebApiTutorial

**Comment by komasoftware** [comment] 2015-02-27 09:53
Here is some more output. I am using the GAE edition.
```
FINE: Get parameters [Fri Feb 27 10:52:26 CET 2015]
INFO: Create a new cell of type webapidescriptor [Fri Feb 27 10:52:26 CET 2015]
FINE: Error during call to GET https://apispark.restlet.com/api/apis/?type=rwadef&cellType=webapidescriptor HTTPS/1.1 [Fri Feb 27 10:52:28 CET 2015]
SEVERE: Introspection error [Fri Feb 27 10:52:28 CET 2015]
```

**Comment by thboileau** [comment] 2015-02-27 09:57
thanks.

as a side note,  I've a made a test to update an existing version and it simply fails for me:
`-u myuserid -p mypasswd  -U --id 6320 -v 1 org.restlet.tutorial.WebApiTutorial`

**Comment by thboileau** [comment] 2015-02-27 14:19
@komasoftware , from what I see in the log traces, your request `Fri Feb 27 10:52:28` may have failed because of the name of the Web API. It seems to contain some special characters.

**Comment by komasoftware** [comment] 2015-03-09 14:44
Is this bug confirmed now or do you want me to test anything else. If I follow the help directives from the tool : 

```
DESCRIPTION
       Publish to the APISpark platform the description of your Web API, represented by
       APPLICATION, the full name of your Restlet or JAX-RS application class or by the Swagger
       definition available at URL/PATH
       If the whole process is successful, it displays the url of the corresponding descriptor or
       connector cell.

EXAMPLES
       org.restlet.ext.apispark.Introspector -u 1234 -p Xy12 --create-descriptor
       com.acme.Application
       org.restlet.ext.apispark.Introspector -u 1234 -p Xy12 --new-version --id 60
       com.acme.Application
       org.restlet.ext.apispark.Introspector -u 1234 -p Xy12 --update --update-strategy replace
       --id 60 --version 1 --language swagger http://acme.com/api/swagger
```

then ``org.restlet.ext.apispark.Introspector -u myuserid -p mypass   --create-descriptor com.klawt.server.ApiBootLoader`` should simply work.

Can you reproduce this error ? And if so, Is this going to be fixed for branch 2.3 ?

**Comment by thboileau** [comment] 2015-03-12 15:32
The new version of APISpark is online since 10 minutes, it contains some bug fix that should help you.
Having said that, I think I have to update the 2.3 branch with the content of the branch apispark-5A.

**Comment by komasoftware** [comment] 2015-03-13 14:12
@thboileau 
I don't see any changes since the updates ... below my results.

** create descriptor **
``Introspector -u myuser-p mypass --create-descriptor com.klawt.server.ApiBootLoader``

 returns 

```
Mar 13, 2015 3:07:39 PM org.restlet.ext.apispark.internal.utils.IntrospectionUtils sendDefinition
INFO: Create a new cell of type webapidescriptor
Mar 13, 2015 3:07:41 PM org.restlet.ext.apispark.Introspector main
SEVERE: Introspection error
java.lang.RuntimeException: APISpark returns client error. Please check the root cause below.
	at org.restlet.ext.apispark.internal.utils.IntrospectionUtils.sendDefinition(IntrospectionUtils.java:159)
	at org.restlet.ext.apispark.Introspector.process(Introspector.java:299)
	at org.restlet.ext.apispark.Introspector.main(Introspector.java:91)
Caused by: Unprocessable Entity (422) - The server understands the content type of the request entity and the syntax of the request entity is correct but was unable to process the contained instructions
	at org.restlet.resource.ClientResource.doError(ClientResource.java:590)
	at org.restlet.resource.ClientResource.handleInbound(ClientResource.java:1153)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1048)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1065)
	at org.restlet.resource.ClientResource.post(ClientResource.java:1466)
	at org.restlet.ext.apispark.internal.utils.IntrospectionUtils.sendDefinition(IntrospectionUtils.java:109)
	... 2 more
```

** new version **

``org.restlet.ext.apispark.Introspector -u myuserid -p mypass --new-version --id 1 com.klawt.server.ApiBootLoader``

 returns

```
Mar 13, 2015 3:10:17 PM org.restlet.ext.apispark.internal.utils.IntrospectionUtils sendDefinition
INFO: Create a new version of the cell 1
Mar 13, 2015 3:10:19 PM org.restlet.ext.apispark.Introspector main
SEVERE: Introspection error
java.lang.RuntimeException: APISpark server encounters some issues, please try later
	at org.restlet.ext.apispark.internal.utils.IntrospectionUtils.sendDefinition(IntrospectionUtils.java:162)
	at org.restlet.ext.apispark.Introspector.process(Introspector.java:299)
	at org.restlet.ext.apispark.Introspector.main(Introspector.java:91)
Caused by: Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ClientResource.doError(ClientResource.java:590)
	at org.restlet.resource.ClientResource.handleInbound(ClientResource.java:1153)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1048)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1065)
	at org.restlet.resource.ClientResource.post(ClientResource.java:1466)
	at org.restlet.ext.apispark.internal.utils.IntrospectionUtils.sendDefinition(IntrospectionUtils.java:115)
	... 2 more
```

**Comment by jlouvel** [comment] 2015-03-14 00:23
Thanks @komasoftware for your help with tests while we investigate your issue.

**Comment by thboileau** [comment] 2015-03-16 15:52
Hi @komasoftware , I've updated the current 2.3 branch, which may help to solve this issue. I think we will publish a new version (2.3.2) in a few days.
I wonder if you can provide us some sample code that allows to reproduce the issue?

**Comment by komasoftware** [comment] 2015-03-16 16:42
@thboileau I pulled in the changes from the 2.3 branch and fired off a new build, but the GWT edition fails to build. Do I open a separate issue for that ?

**Comment by thboileau** [comment] 2015-03-16 16:44
Hi Koen, I take care of that right now.


2015-03-16 17:42 GMT+01:00 Koen <notifications@github.com>:

> @thboileau <https://github.com/thboileau> I pulled in the changes from
> the 2.3 branch and fired off a new build, but the GWT edition fails to
> build. Do I open a separate issue for that ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/restlet/restlet-framework-java/issues/1032#issuecomment-81787990>
> .
>



-- 
*Thierry Boileau, Mr B*
+1 (408) 387-3184 • tboileau@restlet.com

<http://restlet.com/>
6 Rue Rose Dieng-Kuntz • Nantes, 44300 • France

**Comment by komasoftware** [comment] 2015-03-16 17:03
super, thx @thboileau, let me know when I can go ahead.

**Comment by thboileau** [comment] 2015-03-16 17:16
Hi @komasoftware, the fix is now part of the 2.3 branch.

**Comment by komasoftware** [comment] 2015-03-16 22:42
still the same 

** new version **

``org.restlet.ext.apispark.Introspector -u myuserid -p mypass --new-version --id 1 com.klawt.server.ApiBootLoader`` returns 
```
Mar 16, 2015 11:30:27 PM org.restlet.ext.apispark.internal.utils.IntrospectionUtils sendDefinition
INFO: Create a new version of the cell 1
Mar 16, 2015 11:30:29 PM org.restlet.ext.apispark.Introspector main
SEVERE: Introspection error
java.lang.RuntimeException: APISpark server encounters some issues, please try later
	at org.restlet.ext.apispark.internal.utils.IntrospectionUtils.sendDefinition(IntrospectionUtils.java:162)
	at org.restlet.ext.apispark.Introspector.process(Introspector.java:328)
	at org.restlet.ext.apispark.Introspector.main(Introspector.java:121)
Caused by: Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ClientResource.doError(ClientResource.java:590)
	at org.restlet.resource.ClientResource.handleInbound(ClientResource.java:1153)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1048)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1065)
	at org.restlet.resource.ClientResource.post(ClientResource.java:1466)
	at org.restlet.ext.apispark.internal.utils.IntrospectionUtils.sendDefinition(IntrospectionUtils.java:115)
	... 2 more
```
** create descriptor **
``org.restlet.ext.apispark.Introspector -u myuser-p mypass --create-descriptor com.klawt.server.ApiBootLoader``

```
Mar 16, 2015 11:32:15 PM org.restlet.ext.apispark.internal.utils.IntrospectionUtils sendDefinition
INFO: Create a new cell of type webapidescriptor
Mar 16, 2015 11:32:16 PM org.restlet.ext.apispark.Introspector main
SEVERE: Introspection error
java.lang.RuntimeException: APISpark returns client error. Please check the root cause below.
	at org.restlet.ext.apispark.internal.utils.IntrospectionUtils.sendDefinition(IntrospectionUtils.java:159)
	at org.restlet.ext.apispark.Introspector.process(Introspector.java:328)
	at org.restlet.ext.apispark.Introspector.main(Introspector.java:121)
Caused by: Unprocessable Entity (422) - The server understands the content type of the request entity and the syntax of the request entity is correct but was unable to process the contained instructions
	at org.restlet.resource.ClientResource.doError(ClientResource.java:590)
	at org.restlet.resource.ClientResource.handleInbound(ClientResource.java:1153)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1048)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1065)
	at org.restlet.resource.ClientResource.post(ClientResource.java:1466)
	at org.restlet.ext.apispark.internal.utils.IntrospectionUtils.sendDefinition(IntrospectionUtils.java:109)
	... 2 more
```

Here is the code for the Application literally : 

```
@SuppressWarnings("nls")
public class ApiBootLoader extends Application {

	private static Logger log = Logger.getLogger(ApiBootLoader.class.getName());

	public final static boolean productionMode = (SystemProperty.environment.value() == SystemProperty.Environment.Value.Production);

	private boolean started = false;

	private static Router router = null;

	Variable customerId = new Variable(TYPE_DIGIT);
	Variable contactId = new Variable(TYPE_DIGIT);

	public ApiBootLoader() {
		super();
		// register datastore objects with objectify
		ObjectifyInitializer.register();

		CorsService corsService = new CorsService();
		corsService.setSkippingResourceForCorsOptions(true);
		super.getServices().add(corsService);
	}

	@Override
	public synchronized Restlet createInboundRoot() {

		if (!started) {
			super.getConnectorService().getClientProtocols()
					.addAll(Arrays.asList(new Protocol[] { Protocol.HTTP, Protocol.HTTPS }));
			log.info("Setting up inbound root");
			router = new Router(this.getContext());
			router.setRoutingMode(Router.MODE_BEST_MATCH);

			// API
			addAPI(router);
			log.info("Inbound root setup done.");
			started = true;
		}

		return router;
	}

	private void addAPI(Router router) {

		// CONTACT BY ID
		TemplateRoute contactRoute = router.attach(
				String.format("/%s/{%s}", ApiVariables.PATH_CONTACTS, ApiVariables.CONTACT_ID),
				ContactServerResource.class);
		contactRoute.setMatchingMode(MODE_EQUALS);
		Map<String, Variable> contactVariables = contactRoute.getTemplate().getVariables();
		contactVariables.put(ApiVariables.CONTACT_ID, contactId);
		contactVariables.put(ApiVariables.CUSTOMER_ID, customerId);

	}

}
```
Hope that helps !? Nothing exotic AFAIK, but I am running the GAE version.

Isn't there an easy way to turn verbose logging on ? My application uses ``java.util.logging`` but I have been struggling get more output using ``logging.properties`` which worked fine for any every 3rd party library I am using so far.

**Comment by komasoftware** [comment] 2015-03-17 19:42
@thboileau any insights to share ? or can I help to diagnose this issue ?

**Comment by boillodmanuel** [comment] 2015-03-18 11:25
Hi,

The `--new-version` parameter will create a new version for an existing descriptor cell. The `--id` parameter should be the id of this cell.

To find the cell id, click on your cell in apispark and the id is in the URL: `/apis/<cellId>/version/` (1234 in the example below):

![image](https://cloud.githubusercontent.com/assets/621455/6707515/f5739eb4-cd67-11e4-8129-6170d22ac931.png)

We'll update our code to returns an 400 status instead of the 500 status.

**Comment by boillodmanuel** [comment] 2015-03-18 11:49
To investigate deeper in the 422 error, I need the class `ContactServerResource` (only the method signature) and the input / ouput representations classes.

Could you attach it?

**Comment by komasoftware** [comment] 2015-03-18 12:08
Here you go, @boillodmanuel

the ``ContactServerResource`` implements ``ContactResource`` with this signature : 

```
public interface ContactResource {

	@Get
	public Contact retrieve();

	@Delete
	public void destroy();

}
```

And this is the ``Contact`` class, I copied it directly from code and it has a number of dependencies (Objectify annotations, other POJO's, validation annotations, and references to other POJOs). Let me know if you need more info.

```
@SuppressWarnings({ "serial", "nls" })
@Unindex
@Entity
@Cache
@ValidCompany
@ValidPerson
@ValidAncestor(groups = OnSaveValidationGroup.class, message = "Ancestor not set - technical error")
public class Contact implements Serializable, HasContactProfile, DomainResource, AncestorBound<ContactRoot> {

	public static String ORDER_FULLNAME_UP = "fullNameUpperCase";

	public static String ORDER_FULLNAME_DOWN = "-fullNameUpperCase";

	public static String ORDER_LASTMODIFIED_DOWN = "-lastModified";

	public enum ContactStatus {

		ACTIVE,
		INACTIVE;

	}

	public enum ContactType {

		CONTACT,
		CLIENT,
		SUPPLIER,
		CLIENT_SUPPLIER;

		public boolean isClient() {
			return (this.equals(CLIENT) || this.equals(CLIENT_SUPPLIER));
		}

		public boolean isSupplier() {
			return (this.equals(SUPPLIER) || this.equals(CLIENT_SUPPLIER));
		}
		
		public boolean canDelete() {
			return (this.equals(CONTACT));
		}

		public ContactType toClient() {
			ContactType ret = null;
			switch (this) {
			case SUPPLIER:
				ret = CLIENT_SUPPLIER;
				break;
			default:
				ret = CLIENT;
				break;
			}
			return ret;
		}

		public ContactType toSupplier() {
			ContactType ret = null;
			switch (this) {
			case CLIENT:
				ret = CLIENT_SUPPLIER;
				break;
			default:
				ret = SUPPLIER;
				break;
			}
			return ret;
		}

	}

	public enum ContactProfile {

		COMPANY,
		PERSON;

	}

	@Id
	Long id;

	@JsonIgnore
	@Parent
	private Key<ContactRoot> contactRoot;

	@Index
	private Date lastModified = null;

	public Date updated;

	@Size(min = 2, message = "{contact.givenname.size}")
	public String givenName;

	public String additionalName;

	@Size(min = 2, message = "{contact.familyname.size}")
	public String familyName;

	public String namePrefix;

	public String nameSuffix;

	public String fullName;

	@Index
	public String fullNameUpperCase;

	public Date edited;

	@Index
	public List<Long> tags = new ArrayList<Long>();

	public Vat vatField = new Vat();

	@Size(min = 2, message = "{contact.companyname.size}")
	private String companyName;

	@Valid
	public List<PhoneNumber> phoneNumbers = new ArrayList<PhoneNumber>();

	@Index
	@Valid
	public List<EmailAddress> emailAddresses = new ArrayList<EmailAddress>();

	@Valid
	public List<StructuredPostalAddress> addresses = new ArrayList<StructuredPostalAddress>();

	@Index
	public List<String> searchFields = new ArrayList<String>();

	@Index(IfNotNull.class)
	public String givenNameUpperCase;

	@Index(IfNotNull.class)
	public String familyNameUpperCase;

	@Index(IfNotNull.class)
	public String companyNameUpperCase;

	public String photoEtag;

	public List<ContactEvent> contactEvents = new ArrayList<ContactEvent>();

	@NotNull(message = "{contact.status.notnull}")
	@Index
	public ContactStatus status = ContactStatus.ACTIVE;

	@NotNull(message = "{contact.type.notnull}")
	@Index
	ContactType contactType = ContactType.CONTACT;

	@NotNull(message = "{contact.profile.notnull}")
	@Index
	ContactProfile contactProfile = ContactProfile.COMPANY;

	@OnSave
	private void prePersist() {
		lastModified = new Date();
		searchFields = new ArrayList<String>();
		boolean hasGivenName = false;
		// this.title = null;
		this.fullName = "";
		if (givenName != null && givenName.trim().length() > 0) {
			hasGivenName = true;
			fullName = givenName;
			searchFields.addAll(SearchFieldsTokenizer.tokenize(givenName.toUpperCase().toUpperCase()));
			givenNameUpperCase = givenName.toUpperCase();
		} else {
			givenNameUpperCase = null;
		}
		if (familyName != null && familyName.trim().length() > 0) {
			if (hasGivenName) {
				fullName = fullName + " " + familyName;
			} else {
				fullName = familyName;
			}
			searchFields.addAll(SearchFieldsTokenizer.tokenize(familyName.toUpperCase().toUpperCase()));
			familyNameUpperCase = familyName.toUpperCase();
		} else {
			familyNameUpperCase = null;
		}
		if (companyName != null && contactProfile.equals(ContactProfile.COMPANY)) {
			searchFields.addAll(SearchFieldsTokenizer.tokenize(companyName.toUpperCase().toUpperCase()));
			companyNameUpperCase = companyName.toUpperCase();
			if (fullName != null && fullName.length() > 0) {
				fullName = companyName + " (" + fullName + ")";
			} else {
				fullName = companyName;
			}
		} else {
			companyNameUpperCase = null;
		}
		if (vatField != null && vatField.getVatNumber() != null && vatField.getVatNumber().length() > 0) {
			searchFields.add(vatField.getVatNumber().toUpperCase());
		}
		fullNameUpperCase = fullName.toUpperCase();
	}

	@OnLoad
	public void onLoad() {
		if (contactEvents == null) {
			contactEvents = new ArrayList<ContactEvent>();
		}
		if (vatField == null) {
			vatField = new Vat();
		}
	}

	@NotNull(message = "{owner.email.notnull}", groups = OnSaveValidationGroup.class)
	@Index
	String ownerEmail;

	public EmailAddress getDefaultEmailAddress() {
		EmailAddress ret = null;
		if (emailAddresses.size() > 0) {
			for (EmailAddress candidate : emailAddresses) {
				if (candidate.primary) {
					ret = candidate;
					break;
				}
			}
			if (ret == null)
				ret = emailAddresses.get(0);
		}
		return ret;
	}

	public StructuredPostalAddress getDefaultAddress() {
		StructuredPostalAddress ret = null;
		if (addresses.size() > 0) {
			for (StructuredPostalAddress candidate : addresses) {
				if (candidate.primary) {
					ret = candidate;
					break;
				}
			}
			if (ret == null)
				ret = addresses.get(0);
		}
		return ret;
	}

	public PhoneNumber getDefaultPhoneNumber() {
		PhoneNumber ret = null;
		if (phoneNumbers.size() > 0) {
			for (PhoneNumber candidate : phoneNumbers) {
				if (candidate.primary) {
					ret = candidate;
					break;
				}
			}
			if (ret == null)
				ret = phoneNumbers.get(0);
		}
		return ret;
	}

	public Date getEdited() {
		return edited;
	}

	public void setEdited(Date edited) {
		this.edited = edited;
	}

	public List<PhoneNumber> getPhoneNumbers() {
		return phoneNumbers;
	}

	public void setPhoneNumbers(List<PhoneNumber> phoneNumbers) {
		this.phoneNumbers = phoneNumbers;
	}

	public List<EmailAddress> getEmails() {
		return emailAddresses;
	}

	public void setEmails(List<EmailAddress> emailAddress) {
		this.emailAddresses = emailAddress;
	}

	public List<StructuredPostalAddress> getAddresses() {
		return addresses;
	}

	public void setAddresses(List<StructuredPostalAddress> addresses) {
		this.addresses = addresses;
	}

	// public String getTitle() {
	// return title;
	// }

	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Override
	public String toString() {
		return "<" + this.getClass().getName() + ": " + this.getFullName() + ">";
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Override
	public Date getLastModified() {
		return lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public Key<ContactRoot> getContactRoot() {
		return contactRoot;
	}

	public void setContactRoot(Key<ContactRoot> contactRoot) {
		this.contactRoot = contactRoot;
	}

	@Override
	public Object getKey() {
		return id;
	}

	public String getGivenName() {
		return givenName;
	}

	public void setGivenName(String givenName) {
		this.givenName = givenName;
	}

	public String getAdditionalName() {
		return additionalName;
	}

	public void setAdditionalName(String additionalName) {
		this.additionalName = additionalName;
	}

	public String getFamilyName() {
		return familyName;
	}

	public void setFamilyName(String familyName) {
		this.familyName = familyName;
	}

	public String getNamePrefix() {
		return namePrefix;
	}

	public void setNamePrefix(String namePrefix) {
		this.namePrefix = namePrefix;
	}

	public String getNameSuffix() {
		return nameSuffix;
	}

	public void setNameSuffix(String nameSuffix) {
		this.nameSuffix = nameSuffix;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	// public void setTitle(String title) {
	// this.title = title;
	// }

	public List<EmailAddress> getEmailAddresses() {
		return emailAddresses;
	}

	public void setEmailAddresses(List<EmailAddress> emailAddresses) {
		this.emailAddresses = emailAddresses;
	}

	public String getPhotoEtag() {
		return photoEtag;
	}

	public void setPhotoEtag(String photoEtag) {
		this.photoEtag = photoEtag;
	}

	public boolean hasPhoto() {
		return (this.photoEtag != null);
	}

	@Override
	public String getVersion() {
		return "40";
	}

	public List<Long> getTags() {
		return tags;
	}

	public void setTags(List<Long> tags) {
		this.tags = tags;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public ContactStatus getStatus() {
		return status;
	}

	public void setStatus(ContactStatus status) {
		this.status = status;
	}

	public void setVatField(Vat vat) {
		this.vatField = vat;
	}

	public Vat getVatField() {
		return vatField;
	}

	public ContactType getContactType() {
		return contactType;
	}

	public void setContactType(ContactType contactType) {
		this.contactType = contactType;
	}

	public String getCompanyNameUpperCase() {
		return companyNameUpperCase;
	}

	public void setCompanyNameUpperCase(String companyNameUpperCase) {
		this.companyNameUpperCase = companyNameUpperCase;
	}

	public ContactProfile getContactProfile() {
		return contactProfile;
	}

	public void setContactProfile(ContactProfile contactProfile) {
		this.contactProfile = contactProfile;
	}

	@Override
	public Key<ContactRoot> getAncestor() {
		return contactRoot;
	}

	public String getOwnerEmail() {
		return ownerEmail;
	}

	public void setOwnerEmail(String ownerEmail) {
		this.ownerEmail = ownerEmail;
	}

	/**
	 * verifies whether all info is filled out to invoice this contact;
	 * 
	 * @return
	 */
	public boolean isClientComplete() {
		boolean ret = false;
		if (id == null) {
			return false;
		}
		if (addresses.size() == 0) {
			return false;
		}
		if (contactProfile != null && contactProfile.equals(ContactProfile.COMPANY)) {
			return (companyName != null);
		}
		if (contactProfile != null && contactProfile.equals(ContactProfile.PERSON)) {
			return (givenName != null || familyName != null);
		}
		return ret;
	}

	public List<ContactEvent> getContactEvents() {
		return contactEvents;
	}

	public void setContactEvents(List<ContactEvent> contactEvents) {
		this.contactEvents = contactEvents;
	}

	public void toClient() {
		this.contactType = this.contactType.toClient();
	}

	public void toSupplier() {
		this.contactType = this.contactType.toSupplier();
	}

}
```

**Comment by boillodmanuel** [comment] 2015-03-18 18:50
I've just try with your example but I had to comment some properties because I don't know their types (PhoneNumber, EmailAddress, StructuredPostalAddress, ContactEvent, and Key<ContactRoot>).

With the latest version of branch 2.3 (with one fix from today), I cannot reproduce you problem. The descriptor has been created (see here: https://apispark.restlet.com/apis/7069/versions/1/overview).

Could you attach a full sample application (see our [reference application for instrospection](https://github.com/restlet/restlet-sample-descriptor) ) or export the `definition` parameter of `IntrospectionUtils.sendDefinition` to json format via debug and attach it.

Use the following code to export an object to Json:
```
new ObjectMapper().writeValue(System.out, object);
```

By the way, the introspection supports simple Java type (primitive and wrapper), pojo, or collection structure (List, ...). 
Analyzing your code, I suspect your `Key<ContactRoot> getAncestor()` property is not supported.

**Comment by komasoftware** [comment] 2015-03-18 20:44
@boillodmanuel I will look into this. As for the ``Key<ContactRoot>``, I have no problems serializing this type using the JSON or GWT converters. 
I' ll report back. Thx.

**Comment by jlouvel** [comment] 2024-05-11 23:57
Closing as we are removing APISpark/Platform extension in branch 2.5

**Closed by jlouvel** 2024-05-11 23:57 UTC
Labels: Version: 2.3, Priority: high, Extension: APISpark, State: waiting for input
