### ISSUE TITLE
Synchronize with central Maven repository

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#481] opened 2012-03-14 10:43 UTC
Initial ticket : http://restlet.tigris.org/issues/show_bug.cgi?id=497

**Comment by jlouvel** [comment] 2015-08-14 17:37
Another tool mentioned by @glaforge that could help us is Bintray in complement to Sonatype OSS. It can help synchronize to Maven Central:
https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html

**Comment by tdiesler** [comment] 2016-05-11 13:03
No having restlet in central is biting [camel-restlet](https://github.com/apache/camel/blob/master/components/camel-restlet/pom.xml#L40), [wildfly-camel](https://github.com/wildfly-extras/wildfly-camel), [wildfly-swarm](https://github.com/wildfly-swarm/wildfly-swarm-examples/blob/master/camel/pom.xml#L25)

**Comment by jlouvel** [comment] 2016-05-18 20:09
@tdiesler Definitely, we are going to solve this issue as soon as possible. I'm going to try to meet with the Bintray team next week at their SwampUP conference and dig more into this Central sync need.

**Comment by jlouvel** [comment] 2016-05-18 20:36
To get us started, I've created the issue to get the setup in Sonatype OSS repository:
https://issues.sonatype.org/browse/OSSRH-22534

**Comment by jlouvel** [comment] 2016-05-18 20:45
Next steps we'll need to get done are described here:
http://central.sonatype.org/pages/requirements.html

In our case:
- Sign Files with GPG/PGP (see details here: http://central.sonatype.org/pages/working-with-pgp-signatures.html)

Also we'll likely need to:
- Add a dependency on http://maven.restlet.com to make sure special dependencies not in Central are properly resolved

@thboileau Do you think you could take care of those steps sometimes soon?

**Comment by jlouvel** [comment] 2016-05-23 23:17
Sonatype team has been pretty reactive. We are now able to push snapshot to their OSS buffer repository, and do the staging and releases steps, assuming we pass the quality checks (signatures esp.).

**Comment by thboileau** [comment] 2016-05-28 08:38
here are the required steps:
 - complete the metadata of each artefacts (licenses, developpers, SCM Information)
 - sign each artefacts with GPG/PGP

**Comment by janstey** [comment] 2016-12-07 16:25
Is this still planned? Would be really great if restlet was available in Maven central.

**Comment by jlouvel** [comment] 2016-12-08 00:24
There is still a bit of work to do to make it happen, but @thboileau has already done most of it. I'll let him comment on whether he can make it work for RF v2.3, but this is definitely something we have for RF v3.

**Comment by rombert** [comment] 2018-10-25 08:40
@jlouvel @thboileau - if I could be of any assistance please let me know. I've done some migrations to Maven Central in the past and am also interested in seeing this done for a project I'm contributing to ( see [OAK-6880 - Build fails on a fresh m2 repo](https://issues.apache.org/jira/browse/OAK-6880) ).

**Comment by joel-bernstein** [comment] 2019-12-27 21:16
Currently older versions of Apache Solr cannot be built from the main ant-ivy build because of problems resolving the restlet dependencies. 

`[ivy:retrieve] 	==== maven.restlet.org: tried
[ivy:retrieve] 	  http://maven.restlet.org/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
[ivy:retrieve] 	  -- artifact org.restlet.jee#org.restlet.ext.servlet;2.3.0!org.restlet.ext.servlet.jar:
[ivy:retrieve] 	  http://maven.restlet.org/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.jar
[ivy:retrieve] 	==== sonatype-releases: tried
[ivy:retrieve] 	  https://oss.sonatype.org/content/repositories/releases/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
[ivy:retrieve] 	  -- artifact org.restlet.jee#org.restlet.ext.servlet;2.3.0!org.restlet.ext.servlet.jar:
[ivy:retrieve] 	  https://oss.sonatype.org/content/repositories/releases/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.jar
[ivy:retrieve] 	==== releases.cloudera.com: tried
[ivy:retrieve] 	  http://repository.cloudera.com/content/repositories/releases/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
[ivy:retrieve] 	  -- artifact org.restlet.jee#org.restlet.ext.servlet;2.3.0!org.restlet.ext.servlet.jar:
[ivy:retrieve] 	  http://repository.cloudera.com/content/repositories/releases/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.jar
[ivy:retrieve] 	==== working-chinese-mirror: tried
[ivy:retrieve] 	  http://uk.maven.org/maven2/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.pom
[ivy:retrieve] 	  -- artifact org.restlet.jee#org.restlet.ext.servlet;2.3.0!org.restlet.ext.servlet.jar:
[ivy:retrieve] 	  http://uk.maven.org/maven2/org/restlet/jee/org.restlet.ext.servlet/2.3.0/org.restlet.ext.servlet-2.3.0.jar
[ivy:retrieve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve] 		::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve] 		:: org.restlet.jee#org.restlet;2.3.0: not found
[ivy:retrieve] 		:: org.restlet.jee#org.restlet.ext.servlet;2.3.0: not found
[ivy:retrieve] 		::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve] 
[ivy:retrieve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
`
I am working on an a project with a dependency on Solr and it cannot be built from maven:
`Failed to read artifact descriptor for org.restlet.jee:org.restlet:jar:2.3.0: Could not transfer artifact org.restlet.jee:org.restlet:pom:2.3.0 from/to maven-restlet (http://maven.restlet.org): Received fatal alert: handshake_failure`

I also noticed that now there is a redirect to maven.restlet.talend.com when going to maven.restlet.org? Have the maven dependencies been moved for branding reasons? 

Adjusting the pom files to point to the new URL did not resolve the build issues.

Please advise on both the Apache Solr builds and the maven build failures.

**Comment by jlouvel** [comment] 2019-12-30 08:56
Thanks for the report, there is a related issue #1366.

We've recently moved our Maven infrastructure from a custom EC2-based to an S3-based infrastructure as part of the ongoing transition of Restlet to Talend (shared infrastructure).

It seems that the main issue is with the switch from HTTP to HTTPS though rather than the domain name redirection itself. @thboileau and I will keep you updated.

**Comment by rombert** [comment] 2020-01-03 09:39
> It seems that the main issue is with the switch from HTTP to HTTPS though rather than the domain name redirection itself.

I may miss some historical context, but why not "just" deploy the artifacts to Maven Central? Many projects are doing it, ranging from hobbyist projects to whole foundations with custom staging setups (e.g. the Apache Software Foundation).

Your current setup causes problems for current restlet consumers, and I think many of them (myself included) would welcome a change in the repository setup. If there is anything we as consumers can help with (testing,proposing changes) please let us know.

**Comment by jlouvel** [comment] 2020-01-03 09:56
This is definitely the goal, but we historically had some issues with third party libraries especially that were not available in central Maven. With the development of the 2.5 version going on, we should remove all such dependencies which will facilitate this transition to Central and to a full Maven build (vers Ant today).

**Comment by rombert** [comment] 2020-01-06 09:13
Great news, thanks @jlouvel !

**Comment by jlouvel** [comment] 2020-01-09 07:58
FYI, the redirection from maven.restlet.com to maven.restlet.talend.com now preserves the protocol (HTTP or HTTPS).

We are still working on maven.restlet.org redirection infrastructure, but for now to redirects always to HTTP, so it shouldn't break existing builds anymore.

Let us know if you see remaining issues with your builds.

**Comment by breed85** [comment] 2020-01-16 21:16
Hi, 

Our build which includes Solr started failing at about 5 CST Jan 16. It last worked successfully 10:51 CST Jan 14. 

We get a 403 unauthorized from all URLs under maven.restlet.org. If I navigate to restlet.org I get redirected to https://info.talend.com/

Anything you can do to assist is appreciated. Let me know if you need anything further from me.

**Comment by jlouvel** [comment] 2020-01-17 05:49
Hi @breed85 Thanks for the report, I'm looking into this. It's likely related to the deployment of the new redirection from maven.restlet.org to maven.restlet.talend.com.

BTW, the new home of Restlet Framework is https://restlet.talend.com

**Comment by jlouvel** [comment] 2020-01-22 01:18
@breed85  We have completed the deployment of our redirections from maven.restlet.org to maven.restlet.talend.com, and from maven.restlet.com to maven.restlet.talend.com, while preserving the protocol (HTTP or HTTPS).

Can you confirm everything works again for you?

**Comment by breed85** [comment] 2020-01-22 14:44
@jlouvel I can confirm that the build is no longer failing using the original repository definition. I appreciate your quick response. 

Thanks!

**Comment by ashrafsarhan** [comment] 2021-07-20 16:11
I fixed this issue by adding the following repo to my maven pom file 
```
<repository>
    <id>maven-restlet</id>
    <name>Restlet repository</name>
    <url>https://maven.restlet.talend.com</url>
</repository>
 ```

**Comment by jlouvel** [comment] 2024-11-18 03:44
Finally, starting with 2.5 RC1, Restlet Framework is published in Maven Central. Thanks all for your interest in making this happen, it took quite a lot of effort to achieve. See announcement https://github.com/restlet/restlet-framework-java/discussions/1434

**Closed by jlouvel** 2024-11-18 03:44 UTC
Labels: Module: build, Distribution: Maven, State: new, Priority: medium
